---

- name: ensure server_names_hash_bucket_size is not set
  # letsencrypt temporarily overrides this during setup because the hosts it
  # uses for authentication have very long names. The rest of the time the
  # system default should be fine, so we just remove the explicit setting
  # here.
  tags: [ config ]
  lineinfile:
    dest: /etc/nginx/nginx.conf
    state: absent
    regexp: '^\s*server_names_hash_bucket_size'
  notify:
    - validate nginx configuration
    - reload nginx

- name: set SELinux bool which allows nginx to reverse proxy
  tags: [ config ]
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  notify:
    - validate nginx configuration
    - reload nginx

- include: setup-vhost.yml # this includes letsencrypt setup for that host
  with_items: "{{ vhosts }}"
  loop_control:
    loop_var: vhost
