- name: does this vhost have any live letsencrypt certs?
  shell: "[ -d /etc/letsencrypt/live/{{ vhost['host'] }} ]"
  register: live_cert
  ignore_errors: yes

- name: add vhost nginx configs (with SSL if there are live certs)
  tags: [ config ]
  template:
    src: templates/vhost.conf
    dest: /etc/nginx/conf.d/{{ vhost['name'] }}.conf
    owner: nginx
    mode: '640'
  notify:
    - validate nginx configuration
    - reload nginx

- name: if /etc/letsencrypt doesn't exist, set up certs
  # Use certonly because we manage our nginx config, and don't want
  # letsencrypt messing with it
  shell: >
    /opt/certbot/certbot-auto certonly --nginx --agree-tos --quiet
    -m dstrong@glyx.co.uk --domains "{{ vhost.host }}"
  when: live_cert|failed
  register: added_certs

- name: if certs were added update nginx configs
  tags: [ config ]
  template:
    src: templates/vhost.conf
    dest: /etc/nginx/conf.d/{{ vhost['name'] }}.conf
    owner: nginx
    mode: '640'
  when: added_certs|changed
  notify:
    - validate nginx configuration
    - reload nginx
