---

- name: does this vhost have any live letsencrypt certs?
  shell: "[ -d /etc/letsencrypt/live/{{ vhost['host'] }} ]"
  register: has_certs
  ignore_errors: yes

- include: get-new-certs.yml
  when: has_certs|failed

- name: if certs were added update nginx configs
  tags: [ config ]
  template:
    src: templates/vhost.conf
    dest: /etc/nginx/conf.d/{{ vhost['name'] }}.conf
    owner: nginx
    mode: '640'
  notify:
    - validate nginx configuration
    - reload nginx
