---

- name: clone letsencrypt from master
  git:
    repo: https://github.com/certbot/certbot.git
    dest: /opt/certbot

- name: ensure server_names_hash_bucket_size is not set
  # letsencrypt needs to temporarily override this because the hosts it uses
  # for authentication have very long names. The rest of the time the system
  # default should be fine.
  tags: [ config ]
  lineinfile:
    dest: /etc/nginx/nginx.conf
    state: absent
    regexp: '^\s*server_names_hash_bucket_size'
  notify:
    - validate nginx configuration
    - reload nginx

- name: allow nginx to reverse proxy
  tags: [ config ]
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
  notify:
    - validate nginx configuration
    - reload nginx

- include: setup-vhost.yml
  with_items: "{{ vhosts }}"
  loop_control:
    loop_var: vhost

#- name: auto-update certs
    #--domains "{{ vhosts|json_query('[*].host')|join(',') }}"
