server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: {{ url }}

scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/messages
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/secure
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/cron
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/dmesg
- job_name: gogs
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: gogs
      __path__: /var/log/gogs/*.log
- job_name: nginx
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/nginx/*.log
- job_name: letsencrypt
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/letsencrypt/*.log
