server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: {{ url }}

scrape_configs:
- job_name: system
  entry_parser: raw
  static_configs:
  - targets:
      - localhost
    labels:
      host: spark
      type: system
      __path__: /var/log/*.log
  - targets:
      - localhost
    labels:
      host: spark
      __path__: /var/log/messages
  - targets:
      - localhost
    labels:
      host: spark
      __path__: /var/log/secure
  - targets:
      - localhost
    labels:
      host: spark
      __path__: /var/log/cron
  - targets:
      - localhost
    labels:
      host: spark
      __path__: /var/log/dmesg
  - targets:
      - localhost
    labels:
      host: spark
      type: gogs
      __path__: /var/log/gogs/*.log
  - targets:
      - localhost
    labels:
      host: spark
      type: nginx
      __path__: /var/log/nginx/*.log
  - targets:
      - localhost
    labels:
      host: spark
      type: letsencrypt
      __path__: /var/log/letsencrypt/*.log
