---
- name: configure spark
  hosts: spark
  become: true

  vars_files:
    - vars/gogs.yml
    - vars/mutual_tls_client_cert.yml
    - vars/promtail.yml
    - vars/vhosts.yml

  roles:
    - base

    - toolbox

    - gogs

    - role: nginx_reverse_proxy
      vhosts:
        - "{{ gogs_vhost }}"
      client_crt: "{{ client_cert }}"

    - role: promtail
      url: "https://1865:{{ grafana_cloud_api_key }}@logs-us-west1.grafana.net/api/prom/push"
