---
- name: configure spark
  hosts: spark
  become: true

  vars_files:
    - vars/gogs.yml
    - vars/vhosts.yml
    - vars/mutual_tls_client_cert.yml

  roles:
    - base

    - toolbox

    - gogs

    - role: nginx_reverse_proxy
      vhosts:
        - "{{ gogs_vhost }}"
      client_crt: "{{ client_cert }}"
