---
- name: configure spark
  hosts: spark
  become: true
  vars:
    mailgun_smtp_password: "{{ lookup('env', 'MAILGUN_SMTP_PASSWORD') }}"
    gogs_secret_key: "{{ lookup('env', 'GOGS_SECRET_KEY') }}"

  roles:
    - geerlingguy.gogs
    - geerlingguy.nginx

  tasks:
    - name: copy gogs.ini to server
      tags: [ config ]
      template:
        src: templates/gogs.ini
        dest: /home/git/gogs/custom/conf/app.ini
        owner: git
        mode: '640'
      notify:
        - restart gogs

    - name: copy gogs nginx config to server
      tags: [ config ]
      copy:
        src: files/nginx/gogs.conf
        dest: /etc/nginx/conf.d/gogs.conf
        owner: nginx
        mode: '640'
      notify:
        - validate nginx configuration
        - reload nginx
