---
- name: configure spark
  hosts: spark
  become: true

  vars_files:
    - vars/vhosts.yml
    - vars/gogs.yml

  roles:
    - toolbox

    - gogs

    - role: nginx_reverse_proxy
      vhosts:
        - "{{ gogs_vhost }}"
