---

- name: copy custom ssh_keygen_tmp SELinux module to server
  copy:
    src: files/ssh_keygen_tmp.pp
    dest: /root/ssh_keygen_tmp.pp
    owner: root
    mode: '400'
  notify:
    - load ssh_keygen_tmp semodule

- name: create config dirs (/home/git/gogs/custom)
  file:
    path: /home/git/gogs/custom
    state: directory
    owner: git
    mode: '750'

- name: create config dirs (/home/git/gogs/custom/conf)
  file:
    path: /home/git/gogs/custom/conf
    state: directory
    owner: git
    mode: '750'

- name: copy gogs.ini to server
  tags: [ config ]
  template:
    src: templates/gogs.ini
    dest: /home/git/gogs/custom/conf/app.ini
    owner: git
    mode: '640'
  notify:
    - restart gogs
